### ISSUE TITLE
Is there a keylogger functionality in OWA?

### ISSUE THREAD

**Issue by skardach** [Open-Web-Analytics/Open-Web-Analytics#732]
https://github.com/Open-Web-Analytics/Open-Web-Analytics/blob/9b5bdf15560e025b0b4cb5f32ab7f74ec705af33/modules/base/js/owa.tracker.js#L1336

Dear OWA devs, I'd like to understand the part of the code above. Am I correct to think, that owa.tracker.js is enabling a document wide key logging functionality that is limited to all DOM elements which aren't "password" input fields?
If so, does this effectively mean that whenever this script is injected into a site, the analytics owner (in a non-malicious scenario - website owner) has access to all of the text I'm writing in his text fields?
What is the purpose of such logging?

**Comment by padams** [comment]
The feature was developed to help site owners see how people are using a particular web page. It's particularly handy if you are doing usability testing. 

Few people every implement this site wide or for very long as it stores large blobs of serialized data in the db.

Admins have to explicitly turn on the downstream feature in the tracker call and on the server (to record it) in order to use this. It's NOT on by default.

**Comment by semihalf-kardach-stanislaw** [comment]
OK, this makes sense. As I'm not an expert in Web testing, would it be reasonable to display a client-side warning about this feature being enabled? Or otherwise allow users to opt-in?

**Comment by padams** [comment]
That's not typically done as it could bias behavior. There are a number of commercial session recording services and I don't think any of them show a notice but you could check.

**Comment by skardach** [comment]
I agree, it could definitely bias behavior of users. I would argue that this then stops being analytics and starts being a privacy risk but that's beyond the topic of this question.
Thank you for clarifying.
