### ISSUE TITLE
When to use owa_cmds.push() vs OWATracker?

### ISSUE THREAD

**Issue by mariana-s-fernandes** [Open-Web-Analytics/Open-Web-Analytics#852]
**Description**  
When should one use `owa_cmds.push()` vs `OWATracker.trackAction()`?
What are the differences?

**Comment by padams** [comment]
OWATracker.xxxx is the method on the tracker object. Because javasscripts load asynchronously you can't be sure the object exists when you need to call it so we make the owa_cmds queue available to get around that. Essentially the tracker will consume the cmd sent into that queue as soon the tracker is available. Hope that helps.

**Comment by mariana-s-fernandes** [comment]
Thanks for your answer @padams! Does that mean that owa_cmd.push() method is more realiable (ie, works all the time)?

(I was wondering if I should replace the OWATracker.push() by the owa_cmds.trackAction() to send the events in Google Tag Manager.)

**Comment by padams** [comment]
`owa_cmds.push(...)` is the  way to queue up commands and is most reliable l. Not sure how it will interact with Google tag manager.

**Comment by mariana-s-fernandes** [comment]
This was super helpful! I was missing some tracking of events using `OWATracker`, I have changed my code today to use `owa_cmds` instead and I will keep an eye in the next few days to see if I start capturing more data. 🤞
